before_all do
# 	ensure_git_status_clean
end

desc "Rebuild the static HTML"
lane :build do
	sh "cd .. && hugo"
end

desc "Build the required infrastructure on AWS using terraform"
lane :infra do 
	terraform(
		var_file: "private.tfvars",
		state_file: "terraform.tfstate",
		infrastructure_folder: "infrastructure"
	)

	# TODO: Maybe we should not make 2 commits here, but I don't care all that much
	git_commit(
		path: "infrastructure/terraform.tfstate",
		message: "Updated state"
	)
	git_commit(
		path: "infrastructure/terraform.tfstate.backup",
		message: "Updated backup state"
	)
end

desc "Renew SSL certificates with certbot"
lane :ssl do 
	sh "cd .. && certbot --config-dir infrastructure/letsencrypt/config --logs-dir infrastructure/letsencrypt/logs --work-dir infrastructure/letsencrypt/work renew"
end

lane :upload do
	bucket_name = sh "terraform output -state='../infrastructure/terraform.tfstate' s3-bucket-name"
	bucket_name = bucket_name.strip

	upload_folder_to_s3(
		region: "eu-central-1",
		bucket: bucket_name,
		local_path: "public/",
		remote_path: "public",
	)
end

desc "Publish a new version of the website"
lane :publish_site do |opts|
	infra
	ssl
	upload
end

# vim: set ft=ruby:
